formatter: "markdown table"
section:
  show:
    - providers
    - inputs
    - outputs

content: |-
  Email Verification
  ```hcl
  {{ include "email-verification/README.md" }}
  ``` 
  SES Forwarder
  ```hcl
  {{ include "ses-forwarder/README.md" }}
  ``` 
  Verify Domain
  ```hcl
  {{ include "verify-domain/README.md" }}
  ``` 
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}