formatter: "markdown table"
section:
  show:
    - providers
    - inputs
    - outputs

content: |-
  SES Forwarder

module "ses_forwarder" {
  source = "../../"

  sender = ["email@digital.domain.com"]
  to_email = "hello@domain.com"
  domain_name = "digital.domain.com"
  
     tags = {
    Name = "Email-Forwarder"
  }

  Email Verification

  {{ include "email-verification/README.md" }}
   
  SES Forwarder

  {{ include "ses-forwarder/README.md" }}
  
  Verify Domain

  {{ include "verify-domain/README.md" }}
   